const $=id=>document.getElementById(id);let achievements=[],agents=[],walls=[];
function money(v){return '$'+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function date(v){return new Date(v).toLocaleString()}
async function init(){try{await awAuthReady;$('connection').textContent='Connected to Supabase';await Promise.all([loadAchievements(),loadAgents(),loadWalls(),loadConfig()]);renderAll();await awSubscribe({new_achievement:async()=>{await loadAchievements();renderAll()},achievement_updated:async()=>{await loadAchievements();renderAll()},achievement_deleted:async()=>{await loadAchievements();renderAll()},stop_celebration:()=>{}})}catch(e){const detail=e?.message||e?.error_description||String(e);$('connection').textContent='Connection error: '+detail;console.error('Achievement Wall startup error:',e)}}
async function loadAchievements(){const {data,error}=await awSupabase.from('achievements').select('*,agents(name),walls(name,wall_code)').order('created_at',{ascending:false});if(error)throw error;achievements=data||[]}
async function loadAgents(){const {data,error}=await awSupabase.from('agents').select('*').order('name');if(error)throw error;agents=data||[]}
async function loadWalls(){const {data,error}=await awSupabase.from('walls').select('*').order('name');if(error)throw error;walls=data||[]}
async function loadConfig(){const {data}=await awSupabase.from('app_config').select('config').eq('id',1).maybeSingle();if(data?.config){const config=data.config;$('depositDuration').value=config.deposit?.duration||8;$('ftdDuration').value=config.first_time_deposit?.duration||12;$('depositSound').checked=config.deposit?.sound!==false;$('ftdSound').checked=config.first_time_deposit?.sound!==false}}
function renderAll(){renderStats();renderOverviewDetails();renderLeaderboard();renderRecent();renderAgentSelect();renderWallSelect();renderAgents();renderWalls();renderHistory()}
function renderStats(){const totalValue=achievements.reduce((sum,x)=>sum+Number(x.amount||0),0);const registeredWalls=walls.length;const onlineWalls=walls.filter(x=>x.active!==false&&x.last_seen_at&&Date.now()-new Date(x.last_seen_at).getTime()<120000).length;$('statAchievements').textContent=achievements.length;$('statValue').textContent=money(totalValue);$('statWalls').textContent=onlineWalls;if($('statAchievementsSub'))$('statAchievementsSub').textContent=achievements.length===1?'1 recorded achievement':`${achievements.length} recorded achievements`;if($('statValueSub'))$('statValueSub').textContent=`Average: ${money(achievements.length?totalValue/achievements.length:0)}`;if($('statWallsSub'))$('statWallsSub').textContent=`${onlineWalls} online / ${registeredWalls} registered`}


function renderOverviewDetails(){const now=Date.now(),weekStart=now-7*86400000,monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const last7=achievements.filter(a=>new Date(a.created_at).getTime()>=weekStart);const month=achievements.filter(a=>new Date(a.created_at).getTime()>=monthStart.getTime());const totals={};month.forEach(a=>{const name=a.agents?.name||a.name||'Unassigned';totals[name]??={count:0,value:0};totals[name].count++;totals[name].value+=Number(a.amount||0)});const top=Object.entries(totals).sort((a,b)=>b[1].value-a[1].value||b[1].count-a[1].count)[0];const totalValue=achievements.reduce((sum,x)=>sum+Number(x.amount||0),0);if($('last7Achievements'))$('last7Achievements').textContent=`${last7.length} achievement${last7.length===1?'':'s'}`;if($('monthAchievements'))$('monthAchievements').textContent=`${month.length} achievement${month.length===1?'':'s'}`;if($('topPerformer'))$('topPerformer').textContent=top?`${top[0]} · ${money(top[1].value)}`:'No data yet';if($('averageAchievement'))$('averageAchievement').textContent=money(achievements.length?totalValue/achievements.length:0);if($('systemSummary'))$('systemSummary').innerHTML=`<div><span class="status-dot good"></span><strong>Supabase connected</strong></div><div>${agents.length?`${agents.length} agent record${agents.length===1?'':'s'} loaded`:'No agent records found'}</div><div>${walls.length?`${walls.length} wall${walls.length===1?'':'s'} registered`:'No walls registered'}</div>`}

function renderLeaderboard(){const map={};for(const a of achievements){const n=a.agents?.name||a.name;map[n]??={n,count:0,value:0};map[n].count++;map[n].value+=Number(a.amount||0)}const arr=Object.values(map).sort((a,b)=>b.value-a.value||b.count-a.count);$('leaderboard').innerHTML=arr.length?arr.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${esc(x.n)}</strong></td><td>${x.count}</td><td class="amount">${money(x.value)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No achievements yet.</td></tr>'}
function renderRecent(){$('recent').innerHTML=achievements.slice(0,8).map(a=>`<div class="recent-item"><strong>${esc(a.agents?.name||a.name)} <span class="amount">${money(a.amount)}</span></strong><div class="recent-meta">${esc(a.achievement)} · ${date(a.created_at)}</div></div>`).join('')||'<div class="empty">No achievements yet.</div>'}
function renderAgentSelect(){}
function renderWallSelect(){const el=$('wallSelect');if(!el)return;el.innerHTML='<option value="">All walls / main wall</option>'+walls.filter(w=>w.active).map(w=>`<option value="${w.id}">${esc(w.name)} (${esc(w.wall_code)})</option>`).join('')}
function renderAgents(){$('agentsTable').innerHTML=agents.map(a=>`<tr><td><strong>${esc(a.name)}</strong></td><td>${esc(a.team||'General')}</td><td>${a.active?'<span class="badge success">Active</span>':'<span class="badge">Disabled</span>'}</td><td><button class="btn small" onclick="toggleAgent('${a.id}',${!a.active})">${a.active?'Disable':'Enable'}</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No agents.</td></tr>'}
function renderWalls(){$('wallsTable').innerHTML=walls.map(w=>`<tr><td><strong>${esc(w.name)}</strong></td><td><span class="badge">${esc(w.wall_code)}</span></td><td>${esc(w.team||'General')}</td><td>${w.last_seen_at?date(w.last_seen_at):'<span class="danger-text">Not connected</span>'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No walls.</td></tr>'}

function renderHistory(){$('historyTable').innerHTML=achievements.map(a=>`<tr><td>${date(a.created_at)}</td><td><strong>${esc(a.agents?.name||a.name)}</strong></td><td>${esc(a.achievement)}</td><td class="amount">${money(a.amount)}</td><td><span class="badge">${esc(a.theme||'gold')}</span></td><td>${esc(a.walls?.name||'Main')}</td><td><button class="btn small" onclick="editAchievement('${a.id}')">Edit</button> <button class="btn small danger" onclick="deleteAchievement('${a.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No history.</td></tr>'}
async function deleteAchievement(id){const item=achievements.find(a=>a.id===id);if(!item)return;const agentName=item.agents?.name||item.name||'this achievement';if(!confirm(`Delete the achievement for ${agentName}? This cannot be undone.`))return;const {error}=await awSupabase.from('achievements').delete().eq('id',id);if(error){alert('Could not delete achievement: '+error.message);console.error('Delete achievement error:',error);return}await awBroadcast('achievement_deleted',{id});await loadAchievements();renderAll()}
async function editAchievement(id){const item=achievements.find(a=>a.id===id);if(!item)return;const currentName=item.agents?.name||item.name||'';const agentName=prompt('Agent name:',currentName);if(agentName===null)return;const name=agentName.trim();if(!name){alert('Please enter an agent name.');return}const amountText=prompt('Amount:',String(item.amount??0));if(amountText===null)return;const amount=Number(amountText);if(!Number.isFinite(amount)||amount<0){alert('Please enter a valid non-negative amount.');return}const agent=agents.find(a=>a.name.trim().toLowerCase()===name.toLowerCase());const {data,error}=await awSupabase.from('achievements').update({name,agent_id:agent?.id||null,amount}).eq('id',id).select('*,agents(name),walls(name,wall_code)').single();if(error){alert('Could not update deposit: '+error.message);console.error('Edit achievement error:',error);return}await awBroadcast('achievement_updated',data);await loadAchievements();renderAll()}
async function celebrate(){const name=$('agentName').value.trim();if(!name){$('celebrateMsg').textContent='Enter an agent name first.';return}const amount=Number($('amount').value||0);if(!Number.isFinite(amount)||amount<0){$('celebrateMsg').textContent='Enter a valid non-negative amount.';return}const agent=agents.find(a=>a.name.trim().toLowerCase()===name.toLowerCase());const row={name,achievement:$('achievementType').value,amount,agent_id:agent?.id||null,wall_id:null,theme:'gold'};const {data,error}=await awSupabase.from('achievements').insert(row).select('*,agents(name),walls(name,wall_code)').single();if(error){$('celebrateMsg').textContent=error.message;return}await awBroadcast('new_achievement',data);$('celebrateMsg').textContent='🎉 Celebration sent!';$('agentName').value='';$('amount').value='0';await loadAchievements();renderAll()}
async function stop(){await awBroadcast('stop_celebration',{});$('celebrateMsg').textContent='🛑 Stop command sent.'}
async function addAgent(){const name=$('newAgentName').value.trim();if(!name)return;const {error}=await awSupabase.from('agents').insert({name,team:$('newAgentTeam').value.trim()||'General'});if(error){$('connection').textContent='Database error: '+error.message;alert('Could not add agent: '+error.message);console.error('Add agent error:',error);return}$('newAgentName').value='';$('newAgentTeam').value='';await loadAgents();renderAll()}
async function toggleAgent(id,active){await awSupabase.from('agents').update({active}).eq('id',id);await loadAgents();renderAll()}
async function addWall(){const wall_code=$('wallCode').value.trim(),name=$('wallName').value.trim();if(!wall_code||!name)return;const {error}=await awSupabase.from('walls').insert({wall_code,name,team:$('wallTeam').value.trim()||'General'});if(error){alert(error.message);return}$('wallCode').value='';$('wallName').value='';$('wallTeam').value='';await loadWalls();renderAll()}
async function saveSettings(){const {data,error:loadError}=await awSupabase.from('app_config').select('config').eq('id',1).single();if(loadError){$('settingsMsg').textContent=loadError.message;return}const config=data?.config||{};const depositDuration=Math.max(1,Number($('depositDuration').value||8));const ftdDuration=Math.max(1,Number($('ftdDuration').value||12));const depositSound=$('depositSound').checked;const ftdSound=$('ftdSound').checked;config.deposit={...(config.deposit||{}),duration:depositDuration,sound:depositSound};config.first_time_deposit={...(config.first_time_deposit||{}),duration:ftdDuration,sound:ftdSound};const {error}=await awSupabase.from('app_config').update({config,updated_at:new Date().toISOString()}).eq('id',1);if(error){$('settingsMsg').textContent=error.message;return}await awBroadcast('config_updated',config);$('settingsMsg').textContent='Settings saved.'}

document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');$('pageTitle').textContent=b.textContent.replace(/^\S+\s/,'')});$('celebrateBtn').onclick=celebrate;$('stopBtn').onclick=stop;$('addAgent').onclick=addAgent;$('addWall').onclick=addWall;$('saveSettings').onclick=saveSettings;init();
